version: '3'

services:
  db:
    image: mysql:8.0.34
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nest
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: